name: Trigger Contract Terms Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  trigger-contract-terms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Get commit information
      id: commit-info
      run: |
        echo "commit_id=${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "commit_message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
        echo "commit_author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
        echo "commit_url=https://github.com/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_OUTPUT
    
    - name: Trigger contract_terms workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: ERMInc/contract_terms
        event-type: document-updated
        client-payload: |
          {
            "source_repo": "${{ github.repository }}",
            "commit_id": "${{ steps.commit-info.outputs.commit_id }}",
            "commit_message": "${{ steps.commit-info.outputs.commit_message }}",
            "commit_author": "${{ steps.commit-info.outputs.commit_author }}",
            "commit_url": "${{ steps.commit-info.outputs.commit_url }}",
            "branch": "${{ github.ref_name }}",
            "triggered_by": "${{ github.actor }}"
          }
    
    - name: Log trigger event
      run: |
        echo "Successfully triggered contract_terms workflow"
        echo "Source commit: ${{ steps.commit-info.outputs.commit_id }}"
        echo "Commit message: ${{ steps.commit-info.outputs.commit_message }}"
        echo "Branch: ${{ github.ref_name }}"